version: "3.1"

services:
  web:
    build: .
    container_name: chess_web
    volumes:
      - ./src:/src
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure
  nginx:
    image: nginx:alpine
    container_name: chess_nginx
    depends_on:
      - web
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/nginx/certs:/etc/ssl/certs
      - ./frontend/dist:/var/www/html
